# Generated by Django 6.1 on 2026-09-14 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_onetimetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invitation envoyée'), ('PENDING_EMAIL', 'E-mail à confirmer'), ('ACTIVE', 'Actif'), ('REVOKED', 'Accès révoqué')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='onetimetoken',
            name='purpose',
            field=models.CharField(choices=[('EMAIL_VERIFICATION', 'Confirmation d’adresse e-mail'), ('PASSWORD_RESET', 'Réinitialisation du mot de passe'), ('INVITATION', 'Invitation à rejoindre la plateforme')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super administrateur'), ('HIERARCHY', 'Hiérarchie'), ('AGENT', 'Agent terrain')], default='AGENT', max_length=20),
        ),
    ]
