# Generated by Django 6.1 on 2026-09-02 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_socialmedialink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('YOUTUBE', 'YouTube'), ('TIKTOK', 'TikTok')], max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('external_account_id', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('platform',),
            },
        ),
        migrations.CreateModel(
            name='SocialPostAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENT', 'Envoyé'), ('FAILED', 'Échec'), ('SKIPPED', 'Ignoré')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_attempts', to='content.socialaccount')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_attempts', to='content.publicpost')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
