# Generated by Django 6.1 on 2026-09-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_editorimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('YOUTUBE', 'YouTube'), ('TIKTOK', 'TikTok'), ('FACEBOOK', 'Facebook')], max_length=20),
        ),
    ]
