# Generated by Django 6.1 on 2026-09-14 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_publicpost_published_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicmedia',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AddField(
            model_name='publicmedia',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publicmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='publicmedia',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicmedia',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicmedia',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicmedia',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publicmedia',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicmedia',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publicmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='publicmedia',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='needs_reconnect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialpostattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpostattempt',
            name='error_code',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='socialpostattempt',
            name='platform',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='socialpostattempt',
            name='provider_media_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialpostattempt',
            name='provider_post_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialpostattempt',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialpostattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicmedia',
            name='media_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Vidéo'), ('DOCUMENT', 'Document'), ('AUDIO', 'Audio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialpostattempt',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_attempts', to='content.socialaccount'),
        ),
        migrations.AlterField(
            model_name='socialpostattempt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('SENT', 'Envoyé'), ('FAILED', 'Échec'), ('SKIPPED', 'Ignoré')], max_length=20),
        ),
        migrations.CreateModel(
            name='PostLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='content.publicpost')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
