# Generated by Django 6.1 on 2026-09-14 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_backfill_attempt_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpost',
            name='audience',
            field=models.CharField(choices=[('EVERYONE', 'Tout le monde'), ('ALL_AGENTS', 'Tous les agents'), ('HIERARCHY_ONLY', 'Hiérarchie uniquement'), ('SPECIFIC_GROUP', 'Une unité précise'), ('SPECIFIC_USERS', 'Des personnes précises')], default='EVERYONE', max_length=20),
        ),
        migrations.AddField(
            model_name='publicpost',
            name='audience_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publicpost',
            name='audience_users',
            field=models.ManyToManyField(blank=True, related_name='targeted_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicpost',
            name='channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='publicpost',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicpost',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SCHEDULED', 'Programmée'), ('PROCESSING', 'Diffusion en cours'), ('PUBLISHED', 'Publiée'), ('PARTIAL_SUCCESS', 'Publiée partiellement'), ('FAILED', 'Échec de diffusion')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='PublicationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WEB', 'Site / App Web'), ('MOBILE', 'Application mobile'), ('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp'), ('LINKEDIN', 'LinkedIn'), ('YOUTUBE', 'YouTube')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échec'), ('SKIPPED', 'Ignoré')], default='PENDING', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='content.publicpost')),
            ],
            options={
                'ordering': ('channel',),
            },
        ),
        migrations.CreateModel(
            name='PublicationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='content.publicpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-read_at',),
            },
        ),
        migrations.CreateModel(
            name='RecipientDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Envoyé'), ('FAILED', 'Échec'), ('SKIPPED', 'Ignoré')], max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='content.publicationdelivery')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_receipts', to='content.newslettersubscriber')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-sent_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='publicationdelivery',
            constraint=models.UniqueConstraint(fields=('post', 'channel'), name='unique_publication_delivery'),
        ),
        migrations.AddConstraint(
            model_name='publicationread',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_publication_read'),
        ),
        migrations.AddConstraint(
            model_name='recipientdelivery',
            constraint=models.UniqueConstraint(fields=('delivery', 'address'), name='unique_recipient_delivery'),
        ),
    ]
